# Site settings
title: Matt Geary - Conservation Biology
email: mattg533@gmail.com
description: "Personal Website - Matt Geary: Conservation Biology, Ecology, Species Recovery, Reintroduction, Modelling, Habitat, Analysis"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
